defmodule Sca.PublicId do
  @moduledoc """
  Reading and writing human-readable identifiers such as `TN-1` or `CON-42`.

  The values themselves are generated by Postgres — see
  `Sca.Repo.Migration.add_public_id/2`. This module is what the web layers use
  to accept one from a user: parse it, check it belongs to the expected schema,
  and render it back.
  """

  @format ~r/\A(?<prefix>[A-Z][A-Z0-9]{0,7})-(?<number>\d+)\z/

  @doc """
  Prefix configured for a schema, or `nil` when it has no public id.

      Sca.PublicId.prefix(Sca.Tenants.Tenant)
      #=> "TN"
  """
  def prefix(schema) when is_atom(schema) do
    if Code.ensure_loaded?(schema) and function_exported?(schema, :__public_id_prefix__, 0) do
      schema.__public_id_prefix__()
    end
  end

  @doc """
  Builds a public id out of a prefix and a number.

      iex> Sca.PublicId.build("TN", 42)
      "TN-42"
  """
  def build(prefix, number) when is_binary(prefix) and is_integer(number) and number > 0 do
    "#{prefix}-#{number}"
  end

  @doc """
  Splits a public id into its prefix and number.

      iex> Sca.PublicId.parse("TN-42")
      {:ok, "TN", 42}

      iex> Sca.PublicId.parse("nope")
      :error
  """
  def parse(public_id) when is_binary(public_id) do
    case Regex.named_captures(@format, public_id) do
      %{"prefix" => prefix, "number" => number} -> {:ok, prefix, String.to_integer(number)}
      nil -> :error
    end
  end

  def parse(_public_id), do: :error

  @doc """
  Whether the given public id belongs to the given schema.

  Use it before hitting the database, so a `CON-1` typed into a tenant lookup
  is rejected outright instead of silently returning nothing.
  """
  def belongs_to?(public_id, schema) when is_atom(schema) do
    with expected when is_binary(expected) <- prefix(schema),
         {:ok, ^expected, _number} <- parse(public_id) do
      true
    else
      _other -> false
    end
  end
end
