defmodule Sca.Repo.MigrationTest do
  # Runs real DDL outside the sandbox, so it must not run alongside other tests.
  use ExUnit.Case, async: false

  alias Ecto.Adapters.SQL
  alias Sca.Support.PublicIdMigration

  @version 99_999_999_999_999

  setup do
    SQL.Sandbox.mode(Sca.Repo, :auto)
    Ecto.Migrator.up(Sca.Repo, @version, PublicIdMigration, log: false)

    on_exit(fn ->
      Ecto.Migrator.down(Sca.Repo, @version, PublicIdMigration, log: false)
      SQL.Sandbox.mode(Sca.Repo, :manual)
    end)

    :ok
  end

  test "public_id is generated by the database, sequentially, per prefix" do
    assert insert_probe() == "PRB-1"
    assert insert_probe() == "PRB-2"
    assert insert_probe() == "PRB-3"
  end

  test "public_id is unique" do
    insert_probe()

    assert_raise Postgrex.Error, ~r/public_id_probes_public_id_index/, fn ->
      SQL.query!(
        Sca.Repo,
        "INSERT INTO public_id_probes (id, public_id, inserted_at, updated_at) " <>
          "VALUES (gen_random_uuid(), 'PRB-1', now(), now())"
      )
    end
  end

  test "the sequence is dropped together with the table" do
    assert sequence_exists?()

    Ecto.Migrator.down(Sca.Repo, @version, PublicIdMigration, log: false)
    refute sequence_exists?()

    Ecto.Migrator.up(Sca.Repo, @version, PublicIdMigration, log: false)
  end

  defp insert_probe do
    %{rows: [[public_id]]} =
      SQL.query!(
        Sca.Repo,
        "INSERT INTO public_id_probes (id, inserted_at, updated_at) " <>
          "VALUES (gen_random_uuid(), now(), now()) RETURNING public_id"
      )

    public_id
  end

  defp sequence_exists? do
    %{rows: [[count]]} =
      SQL.query!(
        Sca.Repo,
        "SELECT count(*) FROM pg_class WHERE relkind = 'S' AND relname = 'public_id_probes_public_id_seq'"
      )

    count == 1
  end
end
